selected_class:  SimpleMovingAverageStrategy 
#BollingerBandsStrategy
#MomentumRSIStrategy
#SimpleMovingAverageStrategy

obj_name:  simpleMovingAverage
#bollingerBands
#momentumRSI
#simpleMovingAverage